variables:
  BOOST_VERSION: 1.70.0

trigger:
  branches:
    include:
      - testing/2.*

stages:
- stage: Create
  jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        GCC 8:
          CXX: g++-9
          CC: gcc-9
          PACKAGES: g++-9
          CONAN_SETTINGS_OPT: -s compiler=gcc
    steps:
    - bash: |
          set -e
          uname -a
          sudo apt-get update
          sudo apt-get install software-properties-common
      displayName: 'Install: APT'
    - bash: |
          set -e
          uname -a
          sudo apt-add-repository -y "ppa:deadsnakes/ppa"
          sudo apt-get update
          sudo apt-get install python3.6
      displayName: 'Install: Python 3.6'
    - bash: |
          set -e
          uname -a
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          if test -n "${LLVM_REPO}" ; then
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo apt-add-repository "deb http://apt.llvm.org/xenial/ ${LLVM_REPO} main"
          fi
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ${PACKAGES}
      displayName: 'Install: C++'
    - bash: |
          # find / -name python3 -print
          # find / -name pip3 -print
          echo "/usr/bin/python"
          /usr/bin/python --version
          /usr/bin/pip --version
          echo "/usr/bin/python3"
          /usr/bin/python3 --version
          /usr/bin/pip3 --version
          echo "/opt/az/bin/python3"
          /opt/az/bin/python3 --version
          /opt/az/bin/pip3 --version
      displayName: 'Info: Python'
    - bash: |
          set -e
          pip3 install --upgrade pip
          pip3 install --upgrade conan
          pip3 install --upgrade https://github.com/grafikrobot/boost_lib_stats/archive/master.zip
      displayName: 'Install: PIP'
    - bash: |
          set -e
          ./src/script/clone_conan_boost.py "++repo-dir=${HOME}/conan-boost" "++version=${BOOST_VERSION}"
          pushd "${HOME}/conan-boost"
          git submodule foreach git checkout "testing/${BOOST_VERSION}"
      displayName: 'Clone'
    - bash: |
          set -e
          ./src/script/create_all.py "++trace" "++repo-dir=${HOME}/conan-boost" "++version=${BOOST_VERSION}" ${CONAN_SETTINGS_OPT}
      displayName: 'Create'
